### ISSUE TITLE
Possible to set self as "leader"

### ISSUE THREAD

**Issue by dkristian** [lachlang/feedbacker#12]
If a new account is created where the manager email is the same as the person's email, the `PersonDao.create` method will set the leader flag on the new account to true.

Aside, if a user changes their manager, the `setAsLeader` method isn't called for the new manager. This is probably a _good_ thing with the current code, as you could set the leader flag of anyone by temporarily updating the manager email for an account.

**Comment by lachlang** [comment]
This functionality has now been reworked.  Leaders are derived from reporting lines
