### ISSUE TITLE
Nominations type ahead

### ISSUE THREAD

**Issue by lachlang** [lachlang/feedbacker#5]
Current thinking:
- Use angular bootstrap component 
- Statically load full list of names and emails when controller loaded
  - Users will have access anyway, no point in more server calls for the perception of security 
  - Do **not** include guid and manager details in response

**Comment by mkiedys** [comment]
Will you display accounts that await e-mail confirmation?

**Comment by lachlang** [comment]
Good question

I'm thinking probably not.

If the search has not hits a user will still be able to enter an email address explicitly (and that will trigger a notification email).

Given that I don't think it is a need to display non activated accounts.
