### ISSUE TITLE
Questions need additional context or information

### ISSUE THREAD

**Issue by jameshales** [lachlang/feedbacker#7]
Some of the questions refer to objectives, values, risk frameworks, etc. which require additional context or information to adequately answer (particularly if feedback givers are from other parts of the organisation and/or don't already know about the objectives, values, risk frameworks, etc.). The existing feedback spreadsheet contains graphics and information explaining these topics with links to the information on the relevant questions. It would be nice to have the information easily accessible from the question, such as through a link or in-line in the feedback form.

**Comment by lachlang** [comment]
Added ]configurable help text for questions
